# Default initial positions for gen3's ros2_control fake system

initial_positions:
  joint_1: 0
  joint_2: -0.8
  joint_3: -3.15
  joint_4: -2.0
  joint_5: 0.0
  joint_6: -1.2
  joint_7: 1.55
  robotiq_85_left_knuckle_joint: 0
